version: '3.7'

services:
  rabbitmq:
    image: public.ecr.aws/docker/library/rabbitmq:3.11-management-alpine
    networks:
      - rmq
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  rmq:
    name: houseofcat
    external: true
