name: publish

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual Publish'
        required: true
  push:
    branches: [ 'publish' ]
  pull_request:
    branches: [ 'publish' ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.202

    - name: Install dependencies
      run: dotnet restore Tesseract.sln

    - name: Build
      run: dotnet build Tesseract.sln --configuration Release --no-restore

    - name: Publish HouseofCat.Algorithms
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Algorithms/HouseofCat.Algorithms.csproj   
          
    - name: Publish HouseofCat.Compression
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Compression/HouseofCat.Compression.csproj

    - name: Publish HouseofCat.Compression.LZ4
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Compression.LZ4/HouseofCat.Compression.LZ4.csproj

    - name: Publish HouseofCat.Compression.Recyclable
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Compression.Recyclable/HouseofCat.Compression.Recyclable.csproj

    - name: Publish HouseofCat.Dapper
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Dapper/HouseofCat.Dapper.csproj

    - name: Publish HouseofCat.Data
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Data/HouseofCat.Data.csproj

    - name: Publish HouseofCat.Data.Database
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Data.Database/HouseofCat.Data.Database.csproj

    - name: Publish HouseofCat.Data.Parquet
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Data.Parquet/HouseofCat.Data.Parquet.csproj

    - name: Publish HouseofCat.Data.Recyclable
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Data.Recyclable/HouseofCat.Data.Recyclable.csproj

    - name: Publish HouseofCat.Dataflows
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Dataflows/HouseofCat.Dataflows.csproj

    - name: Publish HouseofCat.Dataflows.Pipelines
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Dataflows.Pipelines/HouseofCat.Dataflows.Pipelines.csproj

    - name: Publish HouseofCat.Encryption
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Encryption/HouseofCat.Encryption.csproj

    - name: Publish HouseofCat.Encryption.BouncyCastle
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Encryption.BouncyCastle/HouseofCat.Encryption.BouncyCastle.csproj

    - name: Publish HouseofCat.Encryption.Recyclable
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Encryption.Recyclable/HouseofCat.Encryption.Recyclable.csproj

    - name: Publish HouseofCat.Extensions
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Extensions/HouseofCat.Extensions.csproj

    - name: Publish HouseofCat.Framing
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Framing/HouseofCat.Framing.csproj

    - name: Publish HouseofCat.Gremlins
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Gremlins/HouseofCat.Gremlins.csproj

    - name: Publish HouseofCat.Gremlins.SqlServer
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Gremlins.SqlServer/HouseofCat.Gremlins.SqlServer.csproj

    - name: Publish HouseofCat.Hashing
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Hashing/HouseofCat.Hashing.csproj

    - name: Publish HouseofCat.Hashing.Argon
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Hashing.Argon/HouseofCat.Hashing.Argon.csproj

    - name: Publish HouseofCat.Logger
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Logger/HouseofCat.Logger.csproj

    - name: Publish HouseofCat.Metrics
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Metrics/HouseofCat.Metrics.csproj

    - name: Publish HouseofCat.Metrics.Prometheus
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Metrics.Prometheus/HouseofCat.Metrics.Prometheus.csproj

    - name: Publish HouseofCat.Network
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Network/HouseofCat.Network.csproj

    - name: Publish HouseofCat.RabbitMQ
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ/HouseofCat.RabbitMQ.csproj

    - name: Publish HouseofCat.RabbitMQ.Dataflows
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Dataflows/HouseofCat.RabbitMQ.Dataflows.csproj

    - name: Publish HouseofCat.RabbitMQ.Mailkit
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Mailkit/HouseofCat.RabbitMQ.Mailkit.csproj

    - name: Publish HouseofCat.RabbitMQ.Pipelines
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Pipelines/HouseofCat.RabbitMQ.Pipelines.csproj

    - name: Publish HouseofCat.RabbitMQ.Services
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Services/HouseofCat.RabbitMQ.Services.csproj

    - name: Publish HouseofCat.RabbitMQ.Twilio
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Twilio/HouseofCat.RabbitMQ.Twilio.csproj

    - name: Publish HouseofCat.RabbitMQ.WorkState
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.WorkState/HouseofCat.RabbitMQ.WorkState.csproj

    - name: Publish HouseofCat.Recyclable
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Recyclable/HouseofCat.Recyclable.csproj

    - name: Publish HouseofCat.Reflection
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Reflection/HouseofCat.Reflection.csproj

    - name: Publish HouseofCat.Serialization
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Serialization/HouseofCat.Serialization.csproj

    - name: Publish HouseofCat.Serialization.Json.Newtonsoft
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Serialization.Json.Newtonsoft/HouseofCat.Serialization.Json.Newtonsoft.csproj

    - name: Publish HouseofCat.Serialization.Json.Utf8Json
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Serialization.Json.Utf8Json/HouseofCat.Serialization.Json.Utf8Json.csproj

    - name: Publish HouseofCat.Serialization.MessagePack
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Serialization.MessagePack/HouseofCat.Serialization.MessagePack.csproj

    - name: Publish HouseofCat.Serilog
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Serilog/HouseofCat.Serilog.csproj

    - name: Publish HouseofCat.Sockets
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Sockets/HouseofCat.Sockets.csproj

    - name: Publish HouseofCat.Sockets.Utf8Json
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Sockets.Utf8Json/HouseofCat.Sockets.Utf8Json.csproj

    - name: Publish HouseofCat.Utilities
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Utilities/HouseofCat.Utilities.csproj

    - name: Publish HouseofCat.Windows.Keyboard
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Windows.Keyboard/HouseofCat.Windows.Keyboard.csproj

    - name: Publish HouseofCat.Windows.NativeMethods
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Windows.NativeMethods/HouseofCat.Windows.NativeMethods.csproj

    - name: Publish HouseofCat.Windows.Threading
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Windows.Threading/HouseofCat.Windows.Threading.csproj

    - name: Publish HouseofCat.Windows.WMI
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: version.props
          PROJECT_FILE_PATH: src/HouseofCat.Windows.WMI/HouseofCat.Windows.WMI.csproj
